[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
serenity = "0.12.2"
tokio = "1.39.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
